### ISSUE TITLE
Redesign Home Page

### ISSUE THREAD

**Issue by FabriDamazio** [FabriDamazio/mibli#9]
### Description
The current home page of the Mibli application lacks visual appeal and fails to effectively engage users. To create a more captivating and welcoming experience for visitors, we need to redesign the home page as a beautiful landing page. This redesign should showcase the key features and benefits of the application while providing an aesthetically pleasing interface.

### Tasks
- [ ] Implement the redesigned landing page layout using modern design principles and best practices.
- [ ] Incorporate visually appealing elements such as high-quality images, graphics, and typography to enhance the overall look and feel of the landing page.
- [ ] Highlight the key features and functionalities of the Mibli application in an engaging and concise manner.
- [ ] Ensure that the landing page is responsive and performs well across various devices and screen sizes.
- [ ] Test the redesigned landing page extensively to ensure its functionality, usability, and visual appeal.
- [ ] Gather feedback from users to iterate on the design and address any issues or concerns.
- [ ] Document the design decisions and implementation details of the new landing page for future reference.

### Additional Considerations
- Consider incorporating animations or interactive elements to create a more dynamic and immersive experience for users.
- Optimize the landing page for search engine visibility by including relevant keywords and meta tags.

By redesigning the home page as a beautiful landing page, we aim to attract and retain users, effectively communicate the value proposition of the Mibli application, and ultimately drive conversions and user engagement.

**Comment by FabriDamazio** [comment]
Color palette:

![palette](https://github.com/FabriDamazio/mibli/assets/3181570/db0cecb2-4b52-492a-be57-429b491f97db)

https://coolors.co/fafafa-e3f2fd-db5461-8aa29e-122932

- Tailwind

{ 'seasalt': { DEFAULT: '#fafafa', 100: '#323232', 200: '#646464', 300: '#969696', 400: '#c8c8c8', 500: '#fafafa', 600: '#fbfbfb', 700: '#fcfcfc', 800: '#fdfdfd', 900: '#fefefe' }, 'alice_blue': { DEFAULT: '#e3f2fd', 100: '#06375a', 200: '#0c6eb3', 300: '#2fa0f1', 400: '#89c9f7', 500: '#e3f2fd', 600: '#e8f5fd', 700: '#eef7fe', 800: '#f4fafe', 900: '#f9fcff' }, 'indian_red': { DEFAULT: '#db5461', 100: '#320b0e', 200: '#63151d', 300: '#95202b', 400: '#c72a3a', 500: '#db5461', 600: '#e27580', 700: '#e997a0', 800: '#f0babf', 900: '#f8dcdf' }, 'cambridge_blue': { DEFAULT: '#8aa29e', 100: '#1b2120', 200: '#364341', 300: '#506461', 400: '#6b8681', 500: '#8aa29e', 600: '#a2b5b1', 700: '#b9c7c5', 800: '#d1dad8', 900: '#e8ecec' }, 'gunmetal': { DEFAULT: '#122932', 100: '#04080a', 200: '#071013', 300: '#0b181d', 400: '#0e2027', 500: '#122932', 600: '#295d72', 700: '#4193b3', 800: '#7db8d0', 900: '#bedce7' } }
